spring:
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: http://localhost:8093
          predicates:
            - Path=/products/**
          filters:
            - name: Retry
              args:
                retries: 3
                methods: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
            - name: CircuitBreaker
              args:
                name: product-service
